//=========================================================================================
// Database persisted entity.
// A base abstract class for all persistent entities.
// All model classes stored to a database should be inherited from PersistentEntity.
//=========================================================================================
#pragma once
#include "Stdafx.h"

namespace vms
{
   public ref class PersistentEntity abstract
   {
   protected:
      PersistentEntity() : _id(0) {}      // protected constructor

   public:
      int getId() { return _id; }         // returns the object ID

   private:
      int _id;                            // unique object ID (generated by DB infrastructure)
   };
}
